* A way to corral VCF files

  Please just give me an org-mode file with all my contacts, so I can merge and add stuff at will.

#+BEGIN_SRC shell :export no-eval
manage_contacts .. contacts-from-vcfs.org
#+END_SRC


** Easy personal contact file management
   ~manage_contacts~ is dedicated to collecting contacts in vcf-format for
   contact management.  Some of the features that manage_contacts offers are:
   - read in all vcf-files recursively in a directory
   - output as org-contacts formatted org-file 
   - output as all vcf-files as a single sorted, uniqued vcf-file

** Install

#+BEGIN_SRC shell
pip3 install git+https://github.com/oneyb/manage_contacts
# Or:
git clone https://github.com/oneyb/manage_contacts
cd manage_contacts && python setup.py install
#+END_SRC

*NOTE*: you will need to install it as root or as your user (--user), in order to have the following scripts in the system path.

* TODO Nice to have additions:
  - [ ] Grouping based on tags
  - [ ] automatic merging of disparate info
  - [ ] Output to Google Contacts CSV
  - [ ] Output to VCF with Python from org-mode 
    - Currently, only possible from emacs
* If you want to help
  If you would like to contribute code please include tests.  Please see
  ~tests~ directory.

Run:
#+BEGIN_SRC shell
nosetests -v
#+END_SRC

* Thanks!

Inspired by:
  - Titus von der Malsburg @tmalsburg
    - specifically: https://gist.github.com/tmalsburg/9747104
  - Some other guy from whom I took code
